"""
Streamlit frontend for the Construction Safety Risk Predictor.

The frontend communicates exclusively with the FastAPI service.
It does not load the ML model directly.

This separation mirrors a real production architecture where
the model is served independently from the user interface.
"""

from __future__ import annotations

import io
import os
from typing import Any

import pandas as pd
import requests
import streamlit as st


API_BASE_URL = os.getenv(
    "API_BASE_URL",
    "http://127.0.0.1:8000",
).rstrip("/")

REQUEST_TIMEOUT_SECONDS = 10


REQUIRED_BATCH_COLUMNS = [
    "SA",
    "SK",
    "SN",
    "BA",
    "PBC",
    "reference_point",
    "alpha",
    "beta",
    "lam",
    "day",
]


st.set_page_config(
    page_title="Construction Safety Risk Predictor",
    page_icon="🏗️",
    layout="wide",
)


def api_get(
    endpoint: str,
) -> dict[str, Any]:
    """
    Send a GET request to the FastAPI backend.

    Network errors are converted into clear runtime errors so the
    Streamlit UI can display useful feedback instead of crashing.
    """

    try:
        response = requests.get(
            f"{API_BASE_URL}{endpoint}",
            timeout=REQUEST_TIMEOUT_SECONDS,
        )

        response.raise_for_status()

        return response.json()

    except requests.RequestException as error:
        raise RuntimeError(
            f"API request failed: {error}"
        ) from error


def api_predict(
    payload: dict[str, Any],
) -> dict[str, Any]:
    """
    Send one prediction request to the FastAPI backend.
    """

    try:
        response = requests.post(
            f"{API_BASE_URL}/predict",
            json=payload,
            timeout=REQUEST_TIMEOUT_SECONDS,
        )

        if response.status_code == 422:
            detail = response.json().get(
                "detail",
                "Invalid input data.",
            )

            raise ValueError(
                f"API validation error: {detail}"
            )

        response.raise_for_status()

        return response.json()

    except ValueError:
        raise

    except requests.RequestException as error:
        raise RuntimeError(
            f"Prediction request failed: {error}"
        ) from error


def check_api_health() -> dict[str, Any] | None:
    """
    Return API health information when the backend is available.
    """

    try:
        return api_get(
            "/health"
        )

    except RuntimeError:
        return None


def render_header() -> None:
    """
    Render the project title and research context.
    """

    st.title(
        "🏗️ Construction Safety Risk Predictor"
    )

    st.write(
        "Machine-learning surrogate model trained on "
        "**1,000,000 worker decisions** generated by an "
        "agent-based construction safety simulation."
    )

    st.caption(
        "XGBoost · MLflow · FastAPI · Streamlit · "
        "Simulation-level train/validation/test split"
    )


def render_sidebar() -> None:
    """
    Render backend status and model metadata.
    """

    st.sidebar.header(
        "System Status"
    )

    health = (
        check_api_health()
    )

    if health is None:
        st.sidebar.error(
            "FastAPI backend is unavailable."
        )

        st.sidebar.code(
            API_BASE_URL
        )

        return

    if health.get(
        "status"
    ) == "ok":
        st.sidebar.success(
            "API connected"
        )

    else:
        st.sidebar.warning(
            "API is degraded"
        )

    st.sidebar.write(
        f"**Backend:** `{API_BASE_URL}`"
    )

    try:
        model_info = api_get(
            "/model-info"
        )

        st.sidebar.divider()

        st.sidebar.header(
            "Model"
        )

        st.sidebar.metric(
            "Model",
            model_info.get(
                "model_name",
                "unknown",
            ),
        )

        st.sidebar.metric(
            "Decision threshold",
            f"{model_info.get('decision_threshold', 0):.3f}",
        )

        st.sidebar.metric(
            "Validation Macro F1",
            f"{model_info.get('validation_score', 0):.4f}",
        )

        st.sidebar.write(
            f"**Features:** "
            f"{model_info.get('feature_count', 0)}"
        )

        st.sidebar.write(
            f"**Threshold objective:** "
            f"{model_info.get('threshold_objective', 'N/A')}"
        )

    except RuntimeError:
        st.sidebar.warning(
            "Model metadata unavailable."
        )


def build_single_prediction_payload() -> dict[str, Any]:
    """
    Render sliders and return one valid API payload.
    """

    st.subheader(
        "Worker State"
    )

    left, middle, right = st.columns(
        3
    )

    with left:
        sa = st.slider(
            "Situational Awareness (SA)",
            min_value=0.0,
            max_value=1.0,
            value=0.70,
            step=0.01,
            help=(
                "Worker awareness of hazards "
                "and changing site conditions."
            ),
        )

        sk = st.slider(
            "Safety Knowledge (SK)",
            min_value=0.0,
            max_value=1.0,
            value=0.75,
            step=0.01,
        )

        sn = st.slider(
            "Subjective Norm (SN)",
            min_value=0.0,
            max_value=1.0,
            value=0.68,
            step=0.01,
        )

        ba = st.slider(
            "Behavior Attitude (BA)",
            min_value=0.0,
            max_value=1.0,
            value=0.72,
            step=0.01,
        )

    with middle:
        pbc = st.slider(
            "Perceived Behavior Control (PBC)",
            min_value=0.0,
            max_value=1.0,
            value=0.70,
            step=0.01,
        )

        reference_point = st.slider(
            "CPT Reference Point",
            min_value=0.0,
            max_value=1.0,
            value=0.60,
            step=0.01,
        )

        alpha = st.slider(
            "CPT Alpha",
            min_value=0.10,
            max_value=2.00,
            value=0.88,
            step=0.01,
        )

        beta = st.slider(
            "CPT Beta",
            min_value=0.10,
            max_value=2.00,
            value=0.88,
            step=0.01,
        )

    with right:
        lam = st.slider(
            "Loss Aversion (Lambda)",
            min_value=1.00,
            max_value=2.50,
            value=1.18,
            step=0.01,
        )

        day = st.slider(
            "Simulation Day",
            min_value=0,
            max_value=99,
            value=50,
            step=1,
        )

        intention = (
            sn
            + ba
            + pbc
        ) / 3.0

        st.metric(
            "Calculated Intention",
            f"{intention:.3f}",
        )

        st.caption(
            "Intention is derived automatically as "
            "(SN + BA + PBC) / 3."
        )

    return {
        "SA": sa,
        "SK": sk,
        "SN": sn,
        "BA": ba,
        "PBC": pbc,
        "reference_point": reference_point,
        "alpha": alpha,
        "beta": beta,
        "lam": lam,
        "day": day,
    }


def render_prediction_result(
    result: dict[str, Any],
) -> None:
    """
    Render a single prediction result.
    """

    label = result[
        "label"
    ]

    safe_probability = float(
        result[
            "safe_probability"
        ]
    )

    unsafe_probability = float(
        result[
            "unsafe_probability"
        ]
    )

    threshold = float(
        result[
            "decision_threshold"
        ]
    )

    latency_ms = float(
        result[
            "latency_ms"
        ]
    )

    st.divider()

    st.subheader(
        "Prediction Result"
    )

    if label == "safe":
        st.success(
            "SAFE behavior predicted"
        )

    else:
        st.error(
            "UNSAFE behavior predicted"
        )

    col1, col2, col3, col4 = (
        st.columns(
            4
        )
    )

    col1.metric(
        "Safe probability",
        f"{safe_probability:.1%}",
    )

    col2.metric(
        "Unsafe probability",
        f"{unsafe_probability:.1%}",
    )

    col3.metric(
        "Decision threshold",
        f"{threshold:.3f}",
    )

    col4.metric(
        "API latency",
        f"{latency_ms:.2f} ms",
    )

    st.write(
        "**Safe probability relative to production threshold**"
    )

    st.progress(
        safe_probability
    )

    st.caption(
        f"The model predicts SAFE only when "
        f"P(safe) ≥ {threshold:.3f}. "
        "This threshold was optimized on validation "
        "simulations using Macro F1."
    )


def render_single_prediction() -> None:
    """
    Render interactive single-worker prediction.
    """

    payload = (
        build_single_prediction_payload()
    )

    st.write("")

    if st.button(
        "Predict Safety Behavior",
        type="primary",
        use_container_width=True,
    ):
        try:
            with st.spinner(
                "Requesting prediction..."
            ):
                result = api_predict(
                    payload
                )

            render_prediction_result(
                result
            )

        except (
            RuntimeError,
            ValueError,
        ) as error:
            st.error(
                str(error)
            )


def validate_batch_dataframe(
    dataframe: pd.DataFrame,
) -> list[str]:
    """
    Validate columns required for batch prediction.
    """

    return [
        column
        for column in REQUIRED_BATCH_COLUMNS
        if column
        not in dataframe.columns
    ]


def batch_predict(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Run API predictions for every uploaded CSV row.

    API calls are intentionally used instead of loading the model
    directly so batch and single prediction follow the same
    production inference path.
    """

    output = (
        dataframe.copy()
    )

    labels: list[str] = []
    safe_probabilities: list[
        float
    ] = []
    unsafe_probabilities: list[
        float
    ] = []
    thresholds: list[
        float
    ] = []

    progress = st.progress(
        0.0
    )

    total_rows = len(
        dataframe
    )

    for index, row in (
        dataframe.iterrows()
    ):
        payload = {
            column: (
                int(
                    row[column]
                )
                if column == "day"
                else float(
                    row[column]
                )
            )
            for column in (
                REQUIRED_BATCH_COLUMNS
            )
        }

        result = api_predict(
            payload
        )

        labels.append(
            result["label"]
        )

        safe_probabilities.append(
            result[
                "safe_probability"
            ]
        )

        unsafe_probabilities.append(
            result[
                "unsafe_probability"
            ]
        )

        thresholds.append(
            result[
                "decision_threshold"
            ]
        )

        progress.progress(
            (index + 1)
            / total_rows
        )

    output[
        "prediction"
    ] = labels

    output[
        "safe_probability"
    ] = safe_probabilities

    output[
        "unsafe_probability"
    ] = unsafe_probabilities

    output[
        "decision_threshold"
    ] = thresholds

    return output


def render_batch_prediction() -> None:
    """
    Render CSV batch prediction interface.
    """

    st.subheader(
        "Batch Prediction"
    )

    st.write(
        "Upload a CSV containing the required "
        "worker-state features."
    )

    st.caption(
        "Required columns: "
        + ", ".join(
            REQUIRED_BATCH_COLUMNS
        )
    )

    uploaded_file = (
        st.file_uploader(
            "Upload CSV",
            type=[
                "csv",
            ],
        )
    )

    if uploaded_file is None:
        return

    try:
        dataframe = pd.read_csv(
            uploaded_file
        )

    except Exception as error:
        st.error(
            f"Could not read CSV: {error}"
        )

        return

    st.write(
        f"Rows: **{len(dataframe):,}**"
    )

    st.dataframe(
        dataframe.head(
            20
        ),
        use_container_width=True,
    )

    missing_columns = (
        validate_batch_dataframe(
            dataframe
        )
    )

    if missing_columns:
        st.error(
            "Missing required columns: "
            + ", ".join(
                missing_columns
            )
        )

        return

    if st.button(
        "Run Batch Prediction",
        type="primary",
    ):
        try:
            with st.spinner(
                "Running predictions..."
            ):
                result = (
                    batch_predict(
                        dataframe
                    )
                )

            st.success(
                f"Completed "
                f"{len(result):,} predictions."
            )

            safe_count = int(
                (
                    result[
                        "prediction"
                    ]
                    == "safe"
                ).sum()
            )

            unsafe_count = (
                len(result)
                - safe_count
            )

            first, second = (
                st.columns(
                    2
                )
            )

            first.metric(
                "Predicted safe",
                safe_count,
            )

            second.metric(
                "Predicted unsafe",
                unsafe_count,
            )

            st.dataframe(
                result,
                use_container_width=True,
            )

            csv_buffer = io.StringIO()

            result.to_csv(
                csv_buffer,
                index=False,
            )

            st.download_button(
                label=(
                    "Download Predictions CSV"
                ),
                data=(
                    csv_buffer.getvalue()
                ),
                file_name=(
                    "safety_predictions.csv"
                ),
                mime="text/csv",
            )

        except (
            RuntimeError,
            ValueError,
        ) as error:
            st.error(
                str(error)
            )


def render_monitoring() -> None:
    """
    Render API runtime monitoring metrics.
    """

    st.subheader(
        "API Monitoring"
    )

    try:
        metrics = api_get(
            "/metrics"
        )

    except RuntimeError as error:
        st.error(
            str(error)
        )

        return

    col1, col2, col3, col4 = (
        st.columns(
            4
        )
    )

    col1.metric(
        "Predictions",
        metrics[
            "total_predictions"
        ],
    )

    col2.metric(
        "Safe",
        metrics[
            "safe_predictions"
        ],
    )

    col3.metric(
        "Unsafe",
        metrics[
            "unsafe_predictions"
        ],
    )

    col4.metric(
        "Average latency",
        (
            f"{metrics['average_latency_ms']:.2f} ms"
        ),
    )

    st.caption(
        "Monitoring counters are stored in memory "
        "and reset when the FastAPI service restarts."
    )


def render_methodology() -> None:
    """
    Explain the most important model methodology.
    """

    st.subheader(
        "Methodology"
    )

    st.markdown(
        """
        **Dataset**

        - 100 independent ABM simulation runs
        - 100 workers per run
        - 100 simulated days
        - 1,000,000 worker decisions

        **Leakage-safe split**

        - Train: runs 0–79
        - Validation: runs 80–89
        - Test: runs 90–99

        **Models compared**

        - Logistic Regression
        - Random Forest
        - XGBoost

        **Production model**

        XGBoost was selected using validation Macro F1.

        The production decision threshold was optimized separately
        on validation data and fixed before final test evaluation.

        **Important limitation**

        The labels originate from a stochastic agent-based model.
        Therefore this system is a surrogate model of the simulation,
        not a validated real-world workplace safety system.
        """
    )


def main() -> None:
    """
    Render the complete Streamlit application.
    """

    render_header()

    render_sidebar()

    tab_predict, tab_batch, tab_monitoring, tab_methodology = (
        st.tabs(
            [
                "Single Prediction",
                "Batch Prediction",
                "Monitoring",
                "Methodology",
            ]
        )
    )

    with tab_predict:
        render_single_prediction()

    with tab_batch:
        render_batch_prediction()

    with tab_monitoring:
        render_monitoring()

    with tab_methodology:
        render_methodology()


if __name__ == "__main__":
    main()
